Repository teamOunce/Ounce_Android, pull requests merged in 2020-11, with the labels that each got.

#5 style: Login UI color setting
  app/src/main/res/values/colors.xml
Labels: pull requesst

#6 docs: Add README.md
  README.md
Labels: docs, pull requesst

#8 #3 style: Complete login layout
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/OnBoardingFragment.kt
  app/src/main/res/drawable/img_dummy.png
  app/src/main/res/drawable/temp_kakao_login_large_wide.png
  app/src/main/res/drawable/temp_kakao_login_medium_wide.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/values/strings.xml
Labels: pull requesst, style

#9 #4 feat: Viewpager2 connect adapter and dot indicator
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/login/model/OnBoardingData.kt
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/OnBoardingFragment.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/values/themes.xml
Labels: feat, pull requesst

#15 #14 style: Font add
  app/src/main/res/font/notosans.xml
  app/src/main/res/font/notosans_bold.ttf
  app/src/main/res/font/notosans_regular.ttf
  app/src/main/res/font/notosanskr.xml
  app/src/main/res/font/notosanskr_bold.otf
  app/src/main/res/font/notosanskr_medium.otf
  app/src/main/res/font/notosanskr_regular.otf
  app/src/main/res/layout/fragment_onboarding.xml
Labels: UI, pull requesst, style

#16 #7 docs: README.md modification
  README.md
Labels: docs, pull requesst

#17 chore: Merge login to develop
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/login/model/OnBoardingData.kt
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/OnBoardingFragment.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/res/font/notosans.xml
  app/src/main/res/font/notosans_bold.ttf
  app/src/main/res/font/notosans_regular.ttf
  app/src/main/res/font/notosanskr.xml
  app/src/main/res/font/notosanskr_bold.otf
  app/src/main/res/font/notosanskr_medium.otf
  app/src/main/res/font/notosanskr_regular.otf
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/values/themes.xml
Labels: chore, pull requesst

#20 #19 feat: Status bar TransparentStatusBarObject.kt add
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/util/TransparentStatusBarObject.kt
Labels: UI, feat, pull requesst

#23 #12 chore: Modify codes
  app/build.gradle
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/res/drawable/btn_google_login.xml
  app/src/main/res/drawable/btn_kakao_login.xml
  app/src/main/res/drawable/temp_kakao_login_large_wide.png
  app/src/main/res/drawable/temp_kakao_login_medium_wide.png
  app/src/main/res/layout/activity_login.xml
Labels: chore, pull requesst

#24 #10 #11 feat: welcome, register screen implementation
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/RegisterFragment.kt
  app/src/main/java/com/teamounce/ounce/login/ui/SignUpActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/WelcomeFragment.kt
  app/src/main/res/layout/activity_welcome.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/navigation/navigation_signup.xml
Labels: UI, feat, pull requesst

#25 chore: evening merge
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/RegisterFragment.kt
  app/src/main/java/com/teamounce/ounce/login/ui/SignUpActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/WelcomeFragment.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teamounce/ounce/util/TransparentStatusBarObject.kt
  app/src/main/res/drawable/btn_google_login.xml
  app/src/main/res/drawable/btn_kakao_login.xml
  app/src/main/res/drawable/temp_kakao_login_large_wide.png
  app/src/main/res/drawable/temp_kakao_login_medium_wide.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_welcome.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/navigation/navigation_signup.xml
Labels: chore, pull requesst

#26 #12 feat: Kakao login implementation
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/OunceApplication.kt
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/SignUpActivity.kt
  app/src/main/java/com/teamounce/ounce/singleton/KeyPref.kt
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/navigation/navigation_signup.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Background, pull requesst

#27 chore: night merge
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/OunceApplication.kt
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/SignUpActivity.kt
  app/src/main/java/com/teamounce/ounce/singleton/KeyPref.kt
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/navigation/navigation_signup.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: chore, pull requesst

#28 #18 docs: Update open source list
  README.md
Labels: docs, pull requesst

#29 chore: lunch merge
  README.md
Labels: chore, pull requesst

#30 #22 refactor: Arrange code indenting LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
Labels: pull requesst, refactor

#34 #31 feat: Make function textInputLayout & editText
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/login/ui/RegisterFragment.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/res/anim/slide_in_right.xml
  app/src/main/res/anim/slide_out_left.xml
  app/src/main/res/drawable/button_disabled.xml
  app/src/main/res/drawable/button_enabled.xml
  app/src/main/res/drawable/button_selector.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/navigation/navigation_signup.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: feat, pull requesst

#37 #33 feat: Add signup fragment input layout and button
  app/src/main/java/com/teamounce/ounce/login/ui/RegisterFragment.kt
  app/src/main/res/layout/fragment_register.xml
Labels: feat, pull requesst

#38 #13 feat: Google login add
  app/build.gradle
  app/google-services.json
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  build.gradle
Labels: Background, feat, pull requesst

#39 chore: Initial development of login functionality
  app/build.gradle
  app/google-services.json
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/RegisterFragment.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_register.xml
  build.gradle
Labels: Background, pull requesst

#48 #42 #43 style: Make searchview and result
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/review/ui/SearchActivity.kt
  app/src/main/res/drawable/ic_barcode_search.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_grid.xml
  app/src/main/res/drawable/ic_search_linear.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_food_search_grid.xml
  app/src/main/res/layout/item_food_search_linear.xml
  app/src/main/res/values/colors.xml
Labels: UI, pull requesst, style

#50 #49 feat: Make search recyclerview adapter and switching
  app/build.gradle
  app/src/main/java/com/teamounce/ounce/review/adapter/GridFoodSearchAdapter.kt
  app/src/main/java/com/teamounce/ounce/review/adapter/ListFoodSearchAdapter.kt
  app/src/main/java/com/teamounce/ounce/review/model/CatFood.kt
  app/src/main/java/com/teamounce/ounce/review/ui/SearchActivity.kt
  app/src/main/java/com/teamounce/ounce/singleton/CustomAdapter.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_food_search_grid.xml
  app/src/main/res/layout/item_food_search_linear.xml
Labels: Background, feat, pull requesst

#51 #40 refactor: Onboarding ui refactor
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_onboarding.xml
Labels: UI, pull requesst, refactor

#54 #41 refactor: Change edittext to number picker
  app/src/main/java/com/teamounce/ounce/login/ui/OwnerInfoFragment.kt
  app/src/main/res/layout/fragment_owner_info.xml
Labels: UI, pull requesst, refactor

#55 chore: Merge login client
  app/src/main/java/com/teamounce/ounce/login/ui/OwnerInfoFragment.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/fragment_owner_info.xml
Labels: chore, pull requesst

#56 chore: Merge search
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/review/adapter/GridFoodSearchAdapter.kt
  app/src/main/java/com/teamounce/ounce/review/adapter/ListFoodSearchAdapter.kt
  app/src/main/java/com/teamounce/ounce/review/model/CatFood.kt
  app/src/main/java/com/teamounce/ounce/review/ui/SearchActivity.kt
  app/src/main/java/com/teamounce/ounce/singleton/CustomAdapter.kt
  app/src/main/res/drawable/ic_barcode_search.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_grid.xml
  app/src/main/res/drawable/ic_search_linear.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_food_search_grid.xml
  app/src/main/res/layout/item_food_search_linear.xml
  app/src/main/res/values/colors.xml
Labels: chore, pull requesst

#58 Feature/juyae#46
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/res/drawable/bottom_sheet_box.xml
  app/src/main/res/drawable/bt_diary.png
  app/src/main/res/drawable/bt_drawer.png
  app/src/main/res/drawable/downbar.png
  app/src/main/res/drawable/home_bt_record.png
  app/src/main/res/drawable/home_img_area.png
  app/src/main/res/drawable/image_cat.png
  app/src/main/res/drawable/login_bt_start_activation.png
  app/src/main/res/drawable/mainlogo.png
  app/src/main/res/drawable/pencil.png
  app/src/main/res/drawable/polygon.png
  app/src/main/res/drawable/radio_bt_checked.png
  app/src/main/res/font/applesdgothicneob.ttf
  app/src/main/res/font/applesdgothicneoh.ttf
  app/src/main/res/font/applesdgothicneol.ttf
  app/src/main/res/font/applesdgothicneom.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/bottom_sheet_main.xml
  app/src/main/res/layout/fragment_bottom_main.xml
  app/src/main/res/values/colors.xml
Labels: Juyae, UI, pull requesst

#62 feat: Add search type click listener
  app/src/main/java/com/teamounce/ounce/review/adapter/ListFoodSearchAdapter.kt
  app/src/main/java/com/teamounce/ounce/review/ui/SearchActivity.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/SearchViewModel.kt
  app/src/main/res/color/search_type_selector.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/values/colors.xml
Labels: Background, HyunWoo, pull requesst

#64 feat: Add search type click listener
  app/src/main/java/com/teamounce/ounce/review/adapter/ListFoodSearchAdapter.kt
  app/src/main/java/com/teamounce/ounce/review/ui/SearchActivity.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/SearchViewModel.kt
  app/src/main/res/color/search_type_selector.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/values/colors.xml
Labels: HyunWoo, UI, pull requesst

#66 feat: Set network conntct listener
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/review/ui/SearchActivity.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/SearchViewModel.kt
  app/src/main/res/layout/activity_search.xml
Labels: Background, HyunWoo, feat, pull requesst
