Repository teamOunce/Ounce_Android, pull requests merged in 2021-02, with the labels that each got.

#116 #115 [FEAT] : 조건에 따라 뷰 위치 설정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/OunceApplication.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FoodDetailActivity.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/singleton/BindingAdapters.kt
  app/src/main/java/com/teamounce/ounce/util/PixelUtil.kt
  app/src/main/res/layout/activity_food_detail.xml
  app/src/main/res/values/colors.xml
  build.gradle
Labels: HyunWoo, feat

#118 #117 [FEAT] : Enum Class 사용해서 Preference에 맞게 텍스트 설정
  app/src/main/java/com/teamounce/ounce/feed/repository/mock/MockFeedRepositoryImpl.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FoodDetailActivity.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/Preference.kt
Labels: HyunWoo, feat

#130 Merge l2hyunwoo to develop
  .gitignore
  .idea/misc.xml
  app/build.gradle
  app/src/main/assets/onboarding_img_01.json
  app/src/main/assets/onboarding_img_02.json
  app/src/main/assets/onboarding_img_03.json
  app/src/main/java/com/teamounce/ounce/OunceApplication.kt
  app/src/main/java/com/teamounce/ounce/data/local/singleton/OunceLocalRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/api/LoginService.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/LoginRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/teamounce/ounce/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teamounce/ounce/di/NetworkServiceModule.kt
  app/src/main/java/com/teamounce/ounce/di/RepositoryModule.kt
  app/src/main/java/com/teamounce/ounce/di/RetrofitModule.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FoodDetailActivity.kt
  app/src/main/java/com/teamounce/ounce/feed/viewmodel/FeedViewModel.kt
  app/src/main/java/com/teamounce/ounce/login/adapter/OnBoardingAdapter.kt
  app/src/main/java/com/teamounce/ounce/login/model/OnBoardingData.kt
  app/src/main/java/com/teamounce/ounce/login/model/RequestGoogleLogin.kt
  app/src/main/java/com/teamounce/ounce/login/model/RequestKakaoLogin.kt
  app/src/main/java/com/teamounce/ounce/login/model/ResponseLogin.kt
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/OnBoardingFragment.kt
  app/src/main/java/com/teamounce/ounce/login/ui/SignUpActivity.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ImageSliderFragment.kt
  app/src/main/java/com/teamounce/ounce/review/ui/SearchActivity.kt
  app/src/main/java/com/teamounce/ounce/util/AuthRefreshInterceptor.kt
  app/src/main/java/com/teamounce/ounce/util/BindingAdapters.kt
  app/src/main/java/com/teamounce/ounce/util/StatusBarUtil.kt
  app/src/main/res/drawable/btn_google_login.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/values/colors.xml
  build.gradle
Labels: HyunWoo, feat, pull requesst

#135 Login Activity 종료
  app/build.gradle
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/teamounce/ounce/data/local/singleton/OunceLocalRepository.kt
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teamounce/ounce/util/StatusBarUtil.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: HyunWoo, feat

#143 Merge l2hyunwoo to develop
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/data/local/singleton/OunceLocalRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/api/LoginService.kt
  app/src/main/java/com/teamounce/ounce/data/remote/api/RegisterService.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/FeedRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/LoginRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/RegisterRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/RegisterRepositoryImpl.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/mock/MockFeedRepositoryImpl.kt
  app/src/main/java/com/teamounce/ounce/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teamounce/ounce/di/NetworkServiceModule.kt
  app/src/main/java/com/teamounce/ounce/di/RepositoryModule.kt
  app/src/main/java/com/teamounce/ounce/di/RetrofitModule.kt
  app/src/main/java/com/teamounce/ounce/feed/viewmodel/FeedViewModel.kt
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/login/ui/OwnerInfoFragment.kt
  app/src/main/java/com/teamounce/ounce/login/ui/WelcomeFragment.kt
  app/src/main/java/com/teamounce/ounce/register/model/RequestAddCatInfo.kt
  app/src/main/java/com/teamounce/ounce/register/model/ResponseAddCatInfo.kt
  app/src/main/java/com/teamounce/ounce/register/ui/CatInfoFragment.kt
  app/src/main/java/com/teamounce/ounce/register/ui/SignUpActivity.kt
  app/src/main/java/com/teamounce/ounce/register/ui/UserInfoFragment.kt
  app/src/main/java/com/teamounce/ounce/register/ui/UserInfoTermFragment.kt
  app/src/main/java/com/teamounce/ounce/register/ui/WelcomeFragment.kt
  app/src/main/java/com/teamounce/ounce/register/viewmodel/RegisterViewModel.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsCareActivity.kt
  app/src/main/java/com/teamounce/ounce/util/AuthInterceptor.kt
  app/src/main/java/com/teamounce/ounce/util/BindingAdapters.kt
  app/src/main/java/com/teamounce/ounce/util/LiveDataUtil.kt
  app/src/main/java/com/teamounce/ounce/util/TokenRefreshInterceptor.kt
  app/src/main/res/drawable-v24/toggle_button_selector.xml
  app/src/main/res/drawable/checkbox_selector.xml
  app/src/main/res/drawable/ic_check_bt_checked.xml
  app/src/main/res/drawable/ic_check_bt_unchecked.xml
  app/src/main/res/drawable/img_welcome_background.xml
  app/src/main/res/layout/activity_welcome.xml
  app/src/main/res/layout/fragment_cat_info.xml
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/layout/fragment_user_info_term.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/navigation/navigation_signup.xml
Labels: HyunWoo, feat

#150 Merge l2hyunwoo to develop
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/RetrofitService.kt
  app/src/main/java/com/teamounce/ounce/data/remote/api/MainService.kt
  app/src/main/java/com/teamounce/ounce/data/remote/api/SearchService.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/SearchRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/teamounce/ounce/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teamounce/ounce/di/NetworkServiceModule.kt
  app/src/main/java/com/teamounce/ounce/di/RepositoryModule.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/Comment.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FoodDetailActivity.kt
  app/src/main/java/com/teamounce/ounce/main/BottomSheetAdapter.kt
  app/src/main/java/com/teamounce/ounce/main/BottomSheetFragment.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/main/MainViewRetrofitInterface.kt
  app/src/main/java/com/teamounce/ounce/review/adapter/GridFoodSearchAdapter.kt
  app/src/main/java/com/teamounce/ounce/review/adapter/ResultItemDecoration.kt
  app/src/main/java/com/teamounce/ounce/review/adapter/SearchAdapter.kt
  app/src/main/java/com/teamounce/ounce/review/model/ResponseSearch.kt
  app/src/main/java/com/teamounce/ounce/review/ui/SearchActivity.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/SearchViewModel.kt
  app/src/main/java/com/teamounce/ounce/settings/ui/SettingCareAdapter.kt
  app/src/main/java/com/teamounce/ounce/util/BindingAdapters.kt
  app/src/main/res/drawable/ic_empty_search.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_food_search_grid.xml
  app/src/main/res/layout/item_food_search_linear.xml
Labels: HyunWoo, feat

#151 Feature/#128 kangmin1012
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/feed/adapter/FeedListAdapter.kt
  app/src/main/java/com/teamounce/ounce/feed/model/ResponseFeedListData.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FeedActivity.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FeedBottomSheetDialog.kt
  app/src/main/java/com/teamounce/ounce/feed/viewmodel/FeedActivityViewModel.kt
  app/src/main/java/com/teamounce/ounce/util/BindingAdapterExtension.kt
  app/src/main/res/color/feed_bottom_sheet_select_color.xml
  app/src/main/res/drawable/feed_bottom_sheet_filter_dry_box.xml
  app/src/main/res/drawable/feed_bottom_sheet_filter_wet_box.xml
  app/src/main/res/drawable/ic_dry.xml
  app/src/main/res/drawable/ic_dry_selected.xml
  app/src/main/res/drawable/ic_dry_state.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/ic_hash_tag.xml
  app/src/main/res/drawable/ic_reset.xml
  app/src/main/res/drawable/ic_wet.xml
  app/src/main/res/drawable/ic_wet_selected.xml
  app/src/main/res/drawable/ic_wet_state.xml
  app/src/main/res/font/apple_sd_gothic.xml
  app/src/main/res/layout/activity_feed.xml
  app/src/main/res/layout/item_feed_filter_bottom_sheet.xml
  app/src/main/res/layout/item_feed_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pull requesst

#162 Merge l2hyunwoo to develop
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/data/remote/api/ReviewService.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/ReviewRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/ReviewRepositoryImpl.kt
  app/src/main/java/com/teamounce/ounce/di/NetworkServiceModule.kt
  app/src/main/java/com/teamounce/ounce/di/RepositoryModule.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/review/adapter/CatFoodSliderAdapter.kt
  app/src/main/java/com/teamounce/ounce/review/adapter/SearchAdapter.kt
  app/src/main/java/com/teamounce/ounce/review/model/ResponseRegisterReview.kt
  app/src/main/java/com/teamounce/ounce/review/model/ResponseSearch.kt
  app/src/main/java/com/teamounce/ounce/review/model/ResponseTags.kt
  app/src/main/java/com/teamounce/ounce/review/ui/RecordActivity.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewActivity.kt
  app/src/main/java/com/teamounce/ounce/review/ui/SearchActivity.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/ReviewViewModel.kt
  app/src/main/java/com/teamounce/ounce/util/AuthInterceptor.kt
  app/src/main/java/com/teamounce/ounce/util/BindingAdapters.kt
  app/src/main/java/com/teamounce/ounce/util/ChipFactory.kt
  app/src/main/java/com/teamounce/ounce/util/ImageUri.kt
  app/src/main/res/color/chip_selector.xml
  app/src/main/res/drawable/ic_record_gellary.xml
  app/src/main/res/drawable/ic_tooltip.xml
  app/src/main/res/drawable/record_memo_background.xml
  app/src/main/res/layout/activity_food_detail.xml
  app/src/main/res/layout/activity_record.xml
  app/src/main/res/layout/activity_review.xml
  app/src/main/res/layout/chip_filter.xml
  app/src/main/res/layout/item_catfood_slider.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: HyunWoo, pull requesst

#167 Merge l2hyunwoo to develop
  app/src/main/java/com/teamounce/ounce/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FeedActivity.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewActivity.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewCompleteFragment.kt
  app/src/main/java/com/teamounce/ounce/review/ui/SearchActivity.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ToolTipFragment.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/ReviewViewModel.kt
  app/src/main/res/drawable/bottom_sheet_background.xml
  app/src/main/res/drawable/dialog_background.xml
  app/src/main/res/drawable/ic_complete_enough.xml
  app/src/main/res/drawable/ic_complete_not_enough.xml
  app/src/main/res/drawable/ic_tooltip.xml
  app/src/main/res/drawable/ic_tooltip_quesiton.xml
  app/src/main/res/layout/activity_review.xml
  app/src/main/res/layout/fragment_review_complete.xml
  app/src/main/res/layout/fragment_tool_tip.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: HyunWoo, feat

#171 Merge l2hyunwoo(tag) to develop
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/data/remote/api/TagService.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/FeedRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/TagRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/TagRepositoryImpl.kt
  app/src/main/java/com/teamounce/ounce/di/NetworkServiceModule.kt
  app/src/main/java/com/teamounce/ounce/di/RepositoryModule.kt
  app/src/main/java/com/teamounce/ounce/di/RetrofitModule.kt
  app/src/main/java/com/teamounce/ounce/feed/adapter/ReviewTagAdapter.kt
  app/src/main/java/com/teamounce/ounce/feed/adapter/TagAdapter.kt
  app/src/main/java/com/teamounce/ounce/feed/adapter/TagItemDecoration.kt
  app/src/main/java/com/teamounce/ounce/feed/model/RequestAddTag.kt
  app/src/main/java/com/teamounce/ounce/feed/model/ResponseModifyTagInfo.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FeedActivity.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FoodDetailActivity.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/TagActivity.kt
  app/src/main/java/com/teamounce/ounce/feed/viewmodel/TagViewModel.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/util/BindingAdapters.kt
  app/src/main/java/com/teamounce/ounce/util/ImageUri.kt
  app/src/main/java/com/teamounce/ounce/util/LiveDataUtil.kt
  app/src/main/res/color/edittext_focus_selector.xml
  app/src/main/res/drawable/button_add_selector.xml
  app/src/main/res/drawable/ic_btn_plus.xml
  app/src/main/res/drawable/ic_btn_plus_disable.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/layout/activity_settings_care.xml
  app/src/main/res/layout/activity_tag.xml
  app/src/main/res/layout/item_detail_tag.xml
  app/src/main/res/layout/item_tag_info.xml
  app/src/main/res/values/colors.xml
Labels: HyunWoo, feat, pull requesst

#173 #172 [FIX] : 에러나는 부분 HOTFIX
  .idea/codeStyles/Project.xml
  app/src/main/java/com/teamounce/ounce/settings/SettingsActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsCareActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsIntroActivity.kt
  app/src/main/res/layout/activity_settings_intro.xml
Labels: HyunWoo, pull requesst

#175 Merge Splash
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/SplashActivity.kt
  app/src/main/res/drawable/ic_splash.xml
  app/src/main/res/drawable/splash.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/styles.xml
Labels: HyunWoo, pull requesst

#179 Merge settings to devleop
  app/src/main/java/com/teamounce/ounce/data/local/singleton/OunceLocalRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/api/MainService.kt
  app/src/main/java/com/teamounce/ounce/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingIntroFragment.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsAgreeActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsCareActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsIntroActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsOpensourceActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsPolicyActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/model/ResponseExpire.kt
  app/src/main/java/com/teamounce/ounce/settings/ui/SettingCareAdapter.kt
  app/src/main/java/com/teamounce/ounce/settings/ui/SettingCareViewHolder.kt
  app/src/main/java/com/teamounce/ounce/settings/ui/SettingFragment.kt
  app/src/main/res/drawable-v24/who_made_ounce_img_1.png
  app/src/main/res/drawable-v24/who_made_ounce_img_2.png
  app/src/main/res/drawable-v24/who_made_ounce_img_3.png
  app/src/main/res/drawable/ic_arrow_gray3.xml
  app/src/main/res/drawable/ic_who_made_ounce_bt_left.xml
  app/src/main/res/drawable/ic_who_made_ounce_bt_right.xml
  app/src/main/res/drawable/ic_who_made_ounce_img_1.xml
  app/src/main/res/drawable/ic_who_made_ounce_img_2.xml
  app/src/main/res/drawable/ic_who_made_ounce_img_3.xml
  app/src/main/res/drawable/who_made_ounce_img_1.png
  app/src/main/res/drawable/who_made_ounce_img_2.png
  app/src/main/res/drawable/who_made_ounce_img_3.png
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/activity_settings_agree.xml
  app/src/main/res/layout/activity_settings_care.xml
  app/src/main/res/layout/activity_settings_intro.xml
  app/src/main/res/layout/item_ounceintro.xml
  app/src/main/res/layout/item_setting_catcare.xml
  app/src/main/res/values/colors.xml
Labels: HyunWoo, pull requesst

#183 #182 [FIX] : 뒤로가기 버튼 기능 fix
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/data/remote/api/MainService.kt
  app/src/main/java/com/teamounce/ounce/login/ui/LoginActivity.kt
  app/src/main/java/com/teamounce/ounce/main/BottomSheetFragment.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsAgreeActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsCareActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsIntroActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsOpensourceActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsPolicyActivity.kt
  app/src/main/res/layout/fragment_cat_info.xml
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/layout/fragment_welcome.xml
Labels: HyunWoo, pull requesst

#186 Merge l2hyunwoo to develop
  README.md
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/data/local/singleton/OunceLocalRepository.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/CatRegisterActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/SettingsCareActivity.kt
  app/src/main/res/layout/activity_cat_register.xml
Labels: HyunWoo, feat

#201 Merge l2hyunwoo to develop
  .idea/sonarIssues.xml
  app/src/main/java/com/teamounce/ounce/data/remote/api/FeedService.kt
  app/src/main/java/com/teamounce/ounce/data/remote/api/ReviewService.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/FeedRepository.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/teamounce/ounce/data/remote/repository/mock/MockFeedRepositoryImpl.kt
  app/src/main/java/com/teamounce/ounce/di/RepositoryModule.kt
  app/src/main/java/com/teamounce/ounce/feed/adapter/FeedListAdapter.kt
  app/src/main/java/com/teamounce/ounce/feed/model/Review.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FoodDetailActivity.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/ReviewEditFragment.kt
  app/src/main/java/com/teamounce/ounce/feed/viewmodel/FeedViewModel.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewActivity.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewModifyActivity.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/ReviewViewModel.kt
  app/src/main/res/drawable/ic_review_delete.xml
  app/src/main/res/drawable/ic_review_edit.xml
  app/src/main/res/layout/activity_food_detail.xml
  app/src/main/res/layout/fragment_review_complete.xml
  app/src/main/res/layout/fragment_review_edit.xml
  app/src/main/res/layout/item_detail_tag.xml
Labels: HyunWoo, feat

#202 [FIX]: QA 처리
  .idea/sonarIssues.xml
  app/src/main/java/com/teamounce/ounce/feed/ui/FoodDetailActivity.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/TagActivity.kt
  app/src/main/java/com/teamounce/ounce/register/ui/CatInfoFragment.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewActivity.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewModifyActivity.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/ReviewViewModel.kt
  app/src/main/res/layout/activity_food_detail.xml
  app/src/main/res/layout/activity_review.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_image_slider.xml
  app/src/main/res/layout/item_catfood_slider.xml
  app/src/main/res/layout/item_detail_food.xml
  app/src/main/res/layout/item_food_search_grid.xml
  app/src/main/res/layout/item_food_search_linear.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/values/colors.xml
Labels: HyunWoo, pull requesst

#205 [FIX]: 자동로그인, 카카오로그인 FIX, 메인화면 에러 수정
  .idea/sonarIssues.xml
  app/src/main/assets/home_img_nothing.json
  app/src/main/assets/home_img_step0.json
  app/src/main/assets/home_img_step1.json
  app/src/main/assets/home_img_step2.json
  app/src/main/assets/home_img_step3.json
  app/src/main/assets/home_img_step4.json
  app/src/main/java/com/teamounce/ounce/OunceApplication.kt
  app/src/main/java/com/teamounce/ounce/data/local/singleton/OunceLocalRepository.kt
  app/src/main/java/com/teamounce/ounce/main/BackgroundColor.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/main/ScreenAnimation.kt
  app/src/main/java/com/teamounce/ounce/splash/SplashActivity.kt
  app/src/main/java/com/teamounce/ounce/util/BindingAdapters.kt
  app/src/main/java/com/teamounce/ounce/util/StatusBarUtil.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_onboarding.xml
Labels: HyunWoo, pull requesst

#207 Merge Release 1.0.0 to develop
  .idea/sonarIssues.xml
  app/build.gradle
  app/src/main/assets/home_img_nothing.json
  app/src/main/assets/home_img_step0.json
  app/src/main/assets/home_img_step1.json
  app/src/main/assets/home_img_step2.json
  app/src/main/assets/home_img_step3.json
  app/src/main/assets/home_img_step4.json
  app/src/main/java/com/teamounce/ounce/OunceApplication.kt
  app/src/main/java/com/teamounce/ounce/data/local/singleton/OunceLocalRepository.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/FoodDetailActivity.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/TagActivity.kt
  app/src/main/java/com/teamounce/ounce/main/BackgroundColor.kt
  app/src/main/java/com/teamounce/ounce/main/BottomSheetFragment.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/main/ScreenAnimation.kt
  app/src/main/java/com/teamounce/ounce/register/ui/CatInfoFragment.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewActivity.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewModifyActivity.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/ReviewViewModel.kt
  app/src/main/java/com/teamounce/ounce/settings/adapter/SettingCareAdapter.kt
  app/src/main/java/com/teamounce/ounce/settings/ui/SettingCustomDialog.kt
  app/src/main/java/com/teamounce/ounce/settings/util/SettingCustomDialogBuilder.kt
  app/src/main/java/com/teamounce/ounce/splash/SplashActivity.kt
  app/src/main/java/com/teamounce/ounce/util/BindingAdapters.kt
  app/src/main/java/com/teamounce/ounce/util/SharedPreferences.kt
  app/src/main/java/com/teamounce/ounce/util/StatusBarUtil.kt
  app/src/main/res/drawable/ic_ounce_title.xml
  app/src/main/res/layout/activity_food_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_review.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/fragment_image_slider.xml
  app/src/main/res/layout/fragment_setting_catdltdialog.xml
  app/src/main/res/layout/item_catfood_slider.xml
  app/src/main/res/layout/item_detail_food.xml
  app/src/main/res/layout/item_feed_list.xml
  app/src/main/res/layout/item_food_search_grid.xml
  app/src/main/res/layout/item_food_search_linear.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/layout/item_setting_btn.xml
  app/src/main/res/ounce_title.svg
  app/src/main/res/raw/home_img_nothing.json
  app/src/main/res/raw/home_img_step0.json
  app/src/main/res/raw/home_img_step1.json
  app/src/main/res/raw/home_img_step2.json
  app/src/main/res/raw/home_img_step3.json
  app/src/main/res/raw/home_img_step4.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: HyunWoo, pull requesst

#210 #209 FIX : QA 고치기
  .idea/sonarIssues.xml
  app/build.gradle
  app/src/main/assets/welcome_img.json
  app/src/main/java/com/teamounce/ounce/feed/ui/FoodDetailActivity.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/register/ui/WelcomeFragment.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewModifyActivity.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/ReviewViewModel.kt
  app/src/main/java/com/teamounce/ounce/settings/ui/SettingsActivity.kt
  app/src/main/res/layout/activity_feed.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_settings_agree.xml
  app/src/main/res/layout/activity_settings_policy.xml
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/layout/item_feed_list.xml
  app/src/main/res/layout/item_food_search_linear.xml
Labels: HyunWoo, pull requesst

#211 Version Code Edit
  app/build.gradle
Labels: HyunWoo, fix, pull requesst

#212 [FIX] : QA 부분 수정
  .idea/sonarIssues.xml
  app/src/main/java/com/teamounce/ounce/main/BottomSheetAdapter.kt
  app/src/main/java/com/teamounce/ounce/main/BottomSheetFragment.kt
  app/src/main/java/com/teamounce/ounce/main/MainActivity.kt
  app/src/main/java/com/teamounce/ounce/settings/adapter/SettingCareAdapter.kt
  app/src/main/java/com/teamounce/ounce/settings/adapter/SettingCareViewHolder.kt
  app/src/main/java/com/teamounce/ounce/settings/ui/CatRegisterActivity.kt
  app/src/main/res/layout/item_bottom_main.xml
Labels: HyunWoo, fix, pull requesst

#214 Merge l2hyunwoo_qa to develop
  .idea/sonarIssues.xml
  app/build.gradle
  app/release/output-metadata.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamounce/ounce/OunceApplication.kt
  app/src/main/java/com/teamounce/ounce/feed/ui/TagActivity.kt
  app/src/main/java/com/teamounce/ounce/feed/viewmodel/TagViewModel.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewActivity.kt
  app/src/main/java/com/teamounce/ounce/review/ui/ReviewModifyActivity.kt
  app/src/main/java/com/teamounce/ounce/review/viewmodel/ReviewViewModel.kt
  app/src/main/res/drawable/btn_kakao_login.xml
  app/src/main/res/drawable/ic_icon_back.xml
  app/src/main/res/layout/activity_tag.xml
  app/src/main/res/layout/fragment_review_complete.xml
Labels: HyunWoo, pull requesst
